#ifndef _CONS_H_
#define _CONS_H_

#define TRUE 1
#define FALSE 0

//TYPEDEFS 
typedef unsigned char cmd_id;
typedef int cmd_int;

//SERVER/CLIENT CMDS
#define GET_FLIGHTS_CMD 'A'
#define GET_FLIGHT_INFO_CMD 'B'
#define INSERT_FLIGHT_CMD 'C'
#define DELETE_FLIGHT_CMD 'D'
#define GET_PLANES_CMD 'E'
#define INSERT_PLANE_CMD 'F'
#define DELETE_PLANE_CMD 'G'
#define GET_FLIGHT_RESERVATION_CMD 'H'
#define INSERT_FLIGHT_RESERVATION_CMD 'I'
#define DELETE_FLIGHT_RESERVATION_CMD 'J'
#define LENGTH_CODE_CMD 'L'
#define RESPONSE_CODE_CMD 'R'
#define DISCONNECT_CMD 'Q'

//SERVER/CLIENT CODES
#define CLIENT_RESPONSE_LENGTH_OK 200
#define CLIENT_RESPONSE_LENGTH_ERROR -200 

//SERVER/CLIENT BYTES
#define CMD_BYTES sizeof(cmd_id)
#define CODE_BYTES sizeof(cmd_int)
#define RESPONSE_TOT_BYTES (CMD_BYTES+ CODE_BYTES)
#define LENGTH_TOT_BYTES (CMD_BYTES+ CODE_BYTES)

#endif
 
